CFLAGS=-Wall -Wextra -pedantic -std=c11

test_bits: test_bits.c bits.h
	gcc -o test_bits test_bits.c $(CFLAGS)

mynameis: mynameis.c
	gcc mynameis.c -o mynameis $(CFLAGS)

roll: roll.c
	gcc roll.c -o roll $(CFLAGS)


